---
title: "For Developers"
author: "M Barner"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{For developers}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


We introduce a new 'categorical' vector type and number of specific categorical vector types derived from it.

The categorical vector has the following properties:

*data*:

- a `levels` attribute denoting the unique values the vector can carry (similar to factor levels)
- the levels can be list items, and as such are not restricted to atomic vectors (for example the levels of a `range` vector need to be represented with more than one number each) 
- any number of _alternative_ values corresponding to each level
    - the _alternative_ values are split between _internal alternatives_ and custom alternatives.
    - _internal alternatives_ are predefined for certain subclasses (for example "ranks" for `ordinal` vectors)
    - _custom alternatives_ can be defined by the user; for example different labels for multiple languagues
- each observation in the vector can consist of one or more of the levels, allowing the representation of multiple choice questions.

*methods*:
- `categorical` vectors respond to a method `cat_alternatives()` to change the vector values to one of it's alternatives
-   the resulting vector respond to a method `cat_original()` to revert back to the original vector



From this we built three base types:

- `select`: a character vector with an internal character `label` alternative; good for "select one" and "multiple choice" survey questions
- `ordered`: a character vector with an internal `rank` alternative
- `range` a vector of numeric limits for lower/upper ranges

Each of these comes (where appropriate) with customised

- arithmetics (i.e. adding to `select` vectors could give a vector where both observation's selections are preserved)
- logical operations (i.e. comparing if two vectors with `select` multiple vectors match on _any_ of the sected items)
- conversion functions (i.e. coersion to numeric with `as.numeric`)

